import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { fetchProductBalance } from '@/hooks/useFinishedGoodsStock';

export interface DispatchReturn {
  id: string;
  dispatch_id: string;
  return_number: string;
  return_date: string;
  reason: string | null;
  returned_by: string | null;
  status: string;
  remarks: string | null;
  created_at: string;
}

export interface DispatchReturnItem {
  id: string;
  dispatch_return_id: string;
  dispatch_item_id: string;
  return_qty: number;
  weight_kg: number | null;
  remarks: string | null;
}

export function useDispatchReturns(dispatchId?: string) {
  return useQuery({
    queryKey: ['dispatch_returns', dispatchId],
    enabled: !!dispatchId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('dispatch_returns')
        .select('*')
        .eq('dispatch_id', dispatchId!)
        .order('created_at', { ascending: false });
      if (error) throw error;
      return data as DispatchReturn[];
    },
  });
}

export function useCreateDispatchReturn() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ items, dispatchId, ...returnData }: {
      dispatchId: string;
      reason?: string;
      returned_by?: string;
      remarks?: string;
      items: { dispatch_item_id: string; return_qty: number; weight_kg?: number; remarks?: string }[];
    }) => {
      // Create the return record (return_number auto-generated by trigger)
      const { data, error } = await supabase
        .from('dispatch_returns')
        .insert({
          dispatch_id: dispatchId,
          return_number: '', // trigger will generate
          reason: returnData.reason,
          returned_by: returnData.returned_by,
          remarks: returnData.remarks,
        })
        .select()
        .single();
      if (error) throw error;

      // Insert return items
      const validItems = items.filter(i => i.return_qty > 0);
      if (validItems.length) {
        const returnItems = validItems.map(i => ({ ...i, dispatch_return_id: data.id }));
        const { error: itemErr } = await supabase.from('dispatch_return_items').insert(returnItems);
        if (itemErr) throw itemErr;

        // Restore FG ledger for each returned item
        const dispatchItemIds = validItems.map(i => i.dispatch_item_id);
        const { data: dispatchItems, error: diErr } = await supabase
          .from('dispatch_items')
          .select('id, product_id')
          .in('id', dispatchItemIds);
        if (diErr) throw diErr;

        const productMap = new Map((dispatchItems || []).map(di => [di.id, di.product_id]));

        for (const item of validItems) {
          const productId = productMap.get(item.dispatch_item_id);
          if (!productId) continue;

          const currentStock = await fetchProductBalance(productId);

          // Log stock transaction (ledger IS the stock in Phase 3)
          const { error: txnErr } = await supabase
            .from('stock_transactions')
            .insert({
              product_id: productId,
              quantity: item.return_qty,
              transaction_type: 'dispatch_return',
              reference_type: 'dispatch_return',
              reference_id: data.id,
              remarks: 'Return from dispatch',
              balance_after: currentStock + item.return_qty,
            });
          if (txnErr) throw txnErr;
        }
      }

      // Update dispatch status to returned
      const { error: statusErr } = await supabase
        .from('dispatches')
        .update({ status: 'returned' })
        .eq('id', dispatchId);
      if (statusErr) throw statusErr;

      return data;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['dispatches'] });
      qc.invalidateQueries({ queryKey: ['dispatch_returns'] });
      qc.invalidateQueries({ queryKey: ['finished-goods-stock'] });
      qc.invalidateQueries({ queryKey: ['fg-stock-balances'] });
      qc.invalidateQueries({ queryKey: ['fg-stock-txns'] });
      toast.success('Dispatch return created');
    },
    onError: (e: any) => toast.error('Failed: ' + e.message),
  });
}
