-- =============================================================================
-- Non-destructive stock-ledger fixes  (DRAFT — FOR REVIEW, NOT YET APPLIED)
-- Project: canoplast-v2  (Supabase ref: nreaslganhmdgmuewria)
-- Context: Bossar Nozzle audit discrepancy — see the diagnosis for full detail.
--
-- SCOPE OF THIS FILE (option "b"): structural fixes ONLY.
--   * Adds a monotonic ordering column to stock_transactions.
--   * Replaces two trigger/functions so NEW rows chain correctly and reserves
--     release correctly, going forward.
--   * Adds read-only reconciliation + running-balance views.
--
-- WHAT THIS FILE DELIBERATELY DOES NOT DO (that is Step 3 "data repair",
-- destructive, requires business decisions — kept OUT of this file):
--   * It does NOT rewrite balance_after on existing rows.
--   * It does NOT void/adjust the anomalous -963,000 reserve.
--   * It does NOT release the 101 historical orphaned reserves (-4,441,200).
--   * It does NOT reset component_stock.current_stock for the 43 wrong products.
--   * It does NOT touch the 65 manual ledger_reconciliation adjustments.
--
-- SELF-HEALING BEHAVIOUR: because the new balance trigger derives balance_after
-- from the product's true net (SUM(quantity)), the FIRST new transaction posted
-- for any product will make that product's latest balance_after correct again,
-- without editing history. Historical rows stay as-is until Step 3.
--
-- Idempotent where practical. Review, then apply via Supabase MCP apply_migration.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 1. Monotonic ordering column
-- -----------------------------------------------------------------------------
-- created_at is unreliable for ordering the ledger: production_receipt rows are
-- back-dated to the production time, so "latest by created_at" can point at the
-- wrong row. seq gives a stable, insertion-order tiebreaker for the running
-- view. Adding the column backfills existing rows with identity values in
-- physical order (used only as a tiebreaker; fully reversible via DROP COLUMN).
alter table public.stock_transactions
  add column if not exists seq bigint generated by default as identity;

-- Helps the running-balance view and the per-product balance lookups.
create index if not exists idx_stock_transactions_product_seq
  on public.stock_transactions (product_id, seq);

create index if not exists idx_stock_transactions_product_created
  on public.stock_transactions (product_id, created_at, id);

-- -----------------------------------------------------------------------------
-- 2. Corrected balance trigger (replaces enforce_stock_before_dispatch body)
-- -----------------------------------------------------------------------------
-- OLD behaviour (bugs it fixes):
--   * Only set balance_after for dispatch/assembly_issue/assembly_reserve;
--     production_receipt & adjustment rows were left to app-side values -> drift.
--   * Read "previous balance" as balance_after of the latest row BY created_at,
--     which is corrupted by back-dated inserts.
-- NEW behaviour:
--   * Derives the previous balance from the product's TRUE net (SUM(quantity)),
--     so it is immune to the broken chain and self-heals each product on its
--     next posting.
--   * Serialises concurrent inserts per product with a transaction advisory
--     lock (replaces the old SELECT ... FOR UPDATE on a single row).
--   * Sets balance_after for EVERY transaction type, not just deductions.
--   * Keeps the negative-stock guard, but only for stock-reducing types.
create or replace function public.enforce_stock_before_dispatch()
  returns trigger
  language plpgsql
  set search_path to 'public'
as $function$
declare
  v_prev_net bigint;
  v_code text;
  v_name text;
begin
  if NEW.product_id is null then
    return NEW;  -- nothing to chain
  end if;

  -- Serialise all concurrent inserts for this product so two rows can't read
  -- the same stale net and both compute the same balance_after.
  perform pg_advisory_xact_lock(hashtext(NEW.product_id::text));

  -- True on-hand BEFORE this row = net of every existing movement.
  -- This is deliberately order-independent so a corrupted balance_after chain
  -- cannot poison the new value.
  select coalesce(sum(quantity), 0)
    into v_prev_net
    from public.stock_transactions
   where product_id = NEW.product_id;

  NEW.balance_after := v_prev_net + NEW.quantity;  -- computed, never trusted from caller

  -- Guard only the stock-reducing types. NOTE: until Step 3 clears the
  -- historical orphaned reserves, a handful of products have a negative TRUE
  -- net and legitimate new deductions on them will be blocked here — that is
  -- expected and is the signal that those products need the Step 3 cleanup.
  if NEW.transaction_type in ('dispatch', 'assembly_issue', 'assembly_reserve')
     and NEW.balance_after < 0 then
    select code, name into v_code, v_name from public.products where id = NEW.product_id;
    raise exception
      'Insufficient stock: % (%) has % on hand, this needs %. Short by %.',
      coalesce(v_name, 'Unknown'),
      coalesce(v_code, NEW.product_id::text),
      v_prev_net, abs(NEW.quantity), abs(NEW.balance_after)
      using errcode = 'P0001';
  end if;

  return NEW;
end;
$function$;

-- -----------------------------------------------------------------------------
-- 3. Corrected reserve settlement (replaces settle_assembly_reserves body)
-- -----------------------------------------------------------------------------
-- OLD behaviour (the double-count root cause):
--   Marked assembly_reserve rows settled_at = now(), but NEVER added the
--   reserved quantity back. So reserve(-) AND the later assembly_issue(-) both
--   stayed in the ledger permanently -> stock driven negative.
-- NEW behaviour:
--   For each reserve it settles, it also posts a matching POSITIVE release row
--   (assembly_reserve_release) that reverses the reservation. Net effect of a
--   fully-consumed reserve becomes zero, leaving only the real assembly_issue
--   deduction. The release insert flows through the balance trigger above and
--   gets a correct balance_after.
-- This changes behaviour for FUTURE settlements only; it does not reverse the
-- historical orphaned reserves (that is Step 3).
create or replace function public.settle_assembly_reserves(p_product_id uuid, p_qty numeric)
  returns integer
  language plpgsql
  security definer
  set search_path to 'public'
as $function$
declare
  v_remaining numeric := coalesce(p_qty, 0);
  v_settled_count integer := 0;
  r record;
  v_abs numeric;
begin
  if v_remaining <= 0 then return 0; end if;

  for r in
    select id, quantity
      from public.stock_transactions
     where product_id = p_product_id
       and transaction_type = 'assembly_reserve'
       and settled_at is null
     order by created_at asc, seq asc
  loop
    v_abs := abs(r.quantity);
    if v_remaining >= v_abs then
      -- 1) stamp the reserve settled
      update public.stock_transactions
         set settled_at = now(), settled_by = auth.uid()
       where id = r.id;

      -- 2) reverse the reservation so it stops deducting stock
      insert into public.stock_transactions(
        product_id, transaction_type, quantity, reference_type, reference_id,
        performed_by, remarks)
      values (
        p_product_id, 'assembly_reserve_release', v_abs, 'stock_transactions', r.id,
        auth.uid(),
        'Auto: release of settled assembly_reserve ' || r.id::text);
      -- balance_after is set by the enforce_stock_before_dispatch trigger.

      v_remaining := v_remaining - v_abs;
      v_settled_count := v_settled_count + 1;
    else
      exit;
    end if;
  end loop;

  return v_settled_count;
end;
$function$;

-- -----------------------------------------------------------------------------
-- 4a. Read-only reconciliation view (the guardrail / diagnostic)
-- -----------------------------------------------------------------------------
-- One row per product that has a ledger or a component_stock record. Surfaces
-- the four competing numbers and flags divergence. Use this to watch the repair
-- and to catch future drift. Purely read-only.
create or replace view public.v_stock_reconciliation as
with ledger as (
  select product_id,
         sum(quantity)                          as ledger_net,
         count(*)                               as tx_count,
         sum(case when transaction_type = 'assembly_reserve'
                   and settled_at is null then quantity else 0 end) as unsettled_reserve_qty
    from public.stock_transactions
   group by product_id
),
latest as (
  select distinct on (product_id)
         product_id, balance_after as latest_balance_after
    from public.stock_transactions
   order by product_id, created_at desc, seq desc
)
select
  p.id                                   as product_id,
  p.code,
  p.name,
  cs.current_stock                       as component_current_stock,
  l.ledger_net,
  la.latest_balance_after,
  l.unsettled_reserve_qty,
  l.tx_count,
  (cs.current_stock is distinct from l.ledger_net)               as component_ne_ledger,
  (la.latest_balance_after is distinct from l.ledger_net)        as chain_ne_ledger,
  coalesce(cs.current_stock, 0) - coalesce(l.ledger_net, 0)      as component_minus_ledger
from public.products p
left join ledger l          on l.product_id = p.id
left join latest la         on la.product_id = p.id
left join public.component_stock cs on cs.product_id = p.id
where l.product_id is not null or cs.product_id is not null;

-- -----------------------------------------------------------------------------
-- 4b. Read-only correct running-balance view (for the Stock Ledger Search screen)
-- -----------------------------------------------------------------------------
-- The ledger-search UI should read running_balance from here instead of the
-- stored balance_after column, so it shows a correct, monotonic running total
-- even before the historical balance_after values are repaired in Step 3.
create or replace view public.v_stock_ledger_running as
select
  st.*,
  sum(st.quantity) over (
    partition by st.product_id
    order by st.created_at, st.seq
    rows between unbounded preceding and current row
  ) as running_balance
from public.stock_transactions st;

commit;

-- =============================================================================
-- POST-APPLY SMOKE CHECKS (run manually; read-only)
-- =============================================================================
-- Bossar Nozzle overview:
--   select * from public.v_stock_reconciliation
--    where product_id = 'bc3183d2-7946-45c2-ba32-4d5f71b10a23';
--
-- How many products still diverge (should only shrink as new tx self-heal, and
-- drop sharply after the Step 3 data repair):
--   select count(*) from public.v_stock_reconciliation where component_ne_ledger;
--
-- Verify a new posting self-heals the chain for one product (in a scratch tx):
--   -- insert a test adjustment, confirm balance_after = v_stock_reconciliation.ledger_net, rollback.
-- =============================================================================
